project 'App/Transitions.xcodeproj'

target 'Transitions' do
  use_frameworks!

  pod 'SnapKit'

  target 'TransitionsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TransitionsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
